<a href="https://colab.research.google.com/github/venkataratnamb20/quicksilicon/blob/notebooks/adc_dashboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ADC: Dashboard

In [69]:
import os
import sys
# sys.path.insert(0, os.path.abspath('../..'))
import yaml

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')


import panel as pn
import hvplot.pandas
import holoviews as hv
from holoviews import opts
import param


global_css_files = [
    # "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.css",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css",
    # "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css",
    # pn.template.FastListTemplate.default_css
]
# title_styles = {"border": "1px solid black"}
title_styles = dict(border = "1px solid black",
                    padding = "10px"
                    )

pn.config.raw_css = global_css_files

pn.extension('plotly',
             sizing_mode="stretch_width",
             template="fast",
             design="material",
             loading_indicator=True,
            #  global_css = global_css_files
             )

### Styles

```
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
```

In [90]:

# class="p-5 text-primary bg-primary-subtle border border-primary-subtle rounded-3"

title_wid = pn.pane.HTML("""
<div class="p-1 text-primary bg-primary-subtle text-center">
  <h1>Dashboard</h1>
</div>""", align='center',
                         styles=title_styles
                         )
dashboard = pn.Column(title_wid,
                      pn.Row(*[pn.widgets.Button(name=f"Button {i}", button_type='primary') for i in range(3)], align='center'),
                    )
dashboard.servable()

Column(design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
    [0] HTML(str, align='center', design=<class 'panel.theme.materi..., sizing_mode='stretch_width', styles={'border': '1px solid blac...})
    [1] Row(align='center', design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
        [0] Button(button_type='primary', design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
        [1] Button(button_type='primary', design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
        [2] Button(button_type='primary', design=<class 'panel.theme.materi..., sizing_mode='stretch_width')

# Appendix

## Panel

### templates

In [24]:
widget = pn.widgets.TextInput(value='world')

def hello_world(text):
    return f'Hello {text}!'

pn.Row(widget, pn.bind(hello_world, widget)).servable()

Row(design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
    [0] TextInput(design=<class 'panel.theme.materi..., sizing_mode='stretch_width', value='world')
    [1] ParamFunction(function, _pane=Markdown, defer_load=False, design=<class 'panel.theme.materi..., sizing_mode='stretch_width')

In [38]:

# With Spacer
import panel as pn

pn.extension()

image = pn.pane.PNG("https://assets.holoviz.org/panel/tutorials/wind_turbine.png", sizing_mode="scale_both")

card1 = pn.Card(image, title='Turbine 1', height=150, width=200, align="center")
card2 = pn.Card(image, title='Turbine 2', height=150, width=200, align="center")
spacer1 = pn.Spacer(height=33)
spacer2 = pn.Spacer(height=33)
spacer3 = pn.Spacer(height=33)

pn.Column(
    spacer1, card1, spacer2, card2, spacer3,
    sizing_mode="fixed", width=400, height=400, styles={"border": "1px solid black"}
).servable()

Column(design=<class 'panel.theme.materi..., height=400, sizing_mode='fixed', styles={'border': '1px s...}, width=400)
    [0] Spacer(design=<class 'panel.theme.materi..., height=33, sizing_mode='stretch_width')
    [1] Card(align='center', design=<class 'panel.theme.materi..., height=150, sizing_mode='fixed', title='Turbine 1', width=200)
        [0] PNG(str, design=<class 'panel.theme.materi..., sizing_mode='scale_both')
    [2] Spacer(design=<class 'panel.theme.materi..., height=33, sizing_mode='stretch_width')
    [3] Card(align='center', design=<class 'panel.theme.materi..., height=150, sizing_mode='fixed', title='Turbine 2', width=200)
        [0] PNG(str, design=<class 'panel.theme.materi..., sizing_mode='scale_both')
    [4] Spacer(design=<class 'panel.theme.materi..., height=33, sizing_mode='stretch_width')

In [39]:
# with align and margin
import panel as pn

pn.extension()

image = pn.pane.PNG("https://assets.holoviz.org/panel/tutorials/wind_turbine.png", sizing_mode="scale_both")

card1 = pn.Card(image, title='Turbine 1', height=150, width=200, align="center", margin=(33,0,17,0))
card2 = pn.Card(image, title='Turbine 2', height=150, width=200, align="center", margin=(16,0,33,0))

pn.Column(
    card1, card2,
    sizing_mode="fixed", width=400, height=400, styles={"border": "1px solid black"}
).servable()

Column(design=<class 'panel.theme.materi..., height=400, sizing_mode='fixed', styles={'border': '1px s...}, width=400)
    [0] Card(align='center', design=<class 'panel.theme.materi..., height=150, margin=(33, 0, 17, 0), sizing_mode='fixed', title='Turbine 1', width=200)
        [0] PNG(str, design=<class 'panel.theme.materi..., sizing_mode='scale_both')
    [1] Card(align='center', design=<class 'panel.theme.materi..., height=150, margin=(16, 0, 33, 0), sizing_mode='fixed', title='Turbine 2', width=200)
        [0] PNG(str, design=<class 'panel.theme.materi..., sizing_mode='scale_both')

### Styles

In [40]:
import panel as pn

pn.extension()

outer_style = {
    'background': '#f9f9f9',
    'border-radius': '5px',
    'border': '2px solid black',
    'padding': '20px',
    'box-shadow': '5px 5px 5px #bcbcbc',
    'margin': "10px",
}

pn.indicators.Number(
    name="Wind Speed",
    value=8.6,
    format="{value} m/s",
    colors=[(10, "green"), (100, "red")],
    styles=outer_style,
).servable()

Number(colors=[(10, 'green'), ...], design=<class 'panel.theme.materi..., format='{value} m/s', name='Wind Speed', styles={'background': '#f9f9f9', ...}, value=8.6)

In [41]:
import panel as pn

pn.extension()

outer_style = {
    'background': '#f9f9f9',
    'border-radius': '5px',
    'border': '2px solid black',
    'padding': '20px',
    'box-shadow': '5px 5px 5px #bcbcbc',
    'margin': "10px",
}

inner_stylesheet = """
div:nth-child(2) {
  background-color: pink;
  border-radius: 5px;
  padding: 10px;
  margin: 10px;
}
"""

pn.indicators.Number(
    name="Wind Speed",
    value=8.6,
    format="{value} m/s",
    colors=[(10, "green"), (100, "red")],
    styles=outer_style,
    stylesheets=[inner_stylesheet]
).servable()

Number(colors=[(10, 'green'), ...], design=<class 'panel.theme.materi..., format='{value} m/s', name='Wind Speed', styles={'background': '#f9f9f9', ...}, stylesheets=['\ndiv:nth-child(2) {...], value=8.6)

In [45]:
custom_style = {
    'background': '#f9f9f9',
    'border': '1px solid black',
    'padding': '10px',
    'box-shadow': '5px 5px 5px #bcbcbc'
}

pn.widgets.FloatSlider(name='Number', styles=custom_style)

FloatSlider(design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', styles={'background': '#f9f9f9', ...})

In [46]:
# css variables
stylesheet = """
:host {
  --handle-width: 15px;
  --handle-height: 25px;
  --slider-size: 25px;
}
"""

pn.widgets.FloatSlider(
    name='Number', styles=custom_style, stylesheets=[stylesheet]
)

FloatSlider(design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', styles={'background': '#f9f9f9', ...}, stylesheets=['\n:host {\n  ...])

In [47]:
stylesheet = """
:host {
  --slider-size: 5px;
  --handle-width: 16px;
  --handle-height: 16px;
}

.noUi-handle {
  border-radius: 100%;
  box-shadow: unset;
  background-color: #0081f3;
}
"""

pn.widgets.FloatSlider(
    name='Number', styles=custom_style, stylesheets=[stylesheet]
)

FloatSlider(design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', styles={'background': '#f9f9f9', ...}, stylesheets=['\n:host {\n  ...])

In [48]:
# External Stylesheets
pn.widgets.FloatSlider(
    name='Number', stylesheets=['https://assets.holoviz.org/panel/how_to/styling/noUi.css']
)

FloatSlider(design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', stylesheets=['https://assets.holoviz.o...])

In [50]:
# css classes

color_stylesheet = """
:host(.red) .noUi-handle {
  background-color: red
}

:host(.green) .noUi-handle {
  background-color: green
}

:host(.blue) .noUi-handle {
  background-color: blue
}
"""

pn.Column(
    *(pn.widgets.FloatSlider(name='Number', stylesheets=[stylesheet, color_stylesheet], css_classes=[cls])
      for cls in ('red', 'green', 'blue'))
)

Column(design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
    [0] FloatSlider(css_classes=['red'], design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', stylesheets=['\n:host {\n  --slider-si...])
    [1] FloatSlider(css_classes=['green'], design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', stylesheets=['\n:host {\n  --slider-si...])
    [2] FloatSlider(css_classes=['blue'], design=<class 'panel.theme.materi..., name='Number', sizing_mode='stretch_width', stylesheets=['\n:host {\n  --slider-si...])

### param

In [23]:
import panel as pn

pn.extension(design="material")

component = pn.panel("Hello World")

pn.Row(
    component.param, pn.pane.HTML(component.param._repr_html_())
).servable()

Row(design=<class 'panel.theme.materi..., sizing_mode='stretch_width')
    [0] Column(design=<class 'panel.theme.materi..., margin=(5, 10), name='Markdown', sizing_mode='stretch_width')
        [0] StaticText(design=<class 'panel.theme.materi..., sizing_mode='stretch_width', value='<b>Markdown</b>')
        [1] LiteralInput(description='Whether the object should..., design=<class 'panel.theme.materi..., name='Align', sizing_mode='stretch_width', value='start')
        [2] LiteralInput(description='Describes the proportiona..., design=<class 'panel.theme.materi..., name='Aspect ratio', sizing_mode='stretch_width')
        [3] ListInput(description='CSS classes t..., design=<class 'panel.theme.materi..., name='Css classes', sizing_mode='stretch_width', type=<class 'list'>)
        [4] Row(design=<class 'panel.theme.materi..., width=300)
            [0] Select(description='The design system t..., design=<class 'panel.theme.materi..., margin=(5, 0, 5, 10), name='Design', options=OrderedDict([('None', ...]), sizing_mode='stretch_width', value=<class 'panel.theme.materi...)
            [1] Toggle(align='end', button_type='primary', design=<class 'panel.theme.materi..., height_policy='fit', margin=(0, 0, 5, 10), max_height=30, max_width=20, name='⋮', sizing_mode='stretch_width')
        [5] IntInput(description='The height of the compone..., design=<class 'panel.theme.materi..., name='Height', sizing_mode='stretch_width', start=0)
        [6] IntInput(description='Minimal width o..., design=<class 'panel.theme.materi..., name='Min width', sizing_mode='stretch_width', start=0)
        [7] IntInput(description='Minimal height o..., design=<class 'panel.theme.materi..., name='Min height', sizing_mode='stretch_width', start=0)
        [8] IntInput(description='Minimal width o..., design=<class 'panel.theme.materi..., name='Max width', sizing_mode='stretch_width', start=0)
        [9] IntInput(description='Minimal height o..., design=<class 'panel.theme.materi..., name='Max height', sizing_mode='stretch_width', start=0)
        [10] LiteralInput(description='Allows to create addition..., design=<class 'panel.theme.materi..., name='Margin', sizing_mode='stretch_width', value=(5, 10))
        [11] DictInput(description='Dictionary of C..., design=<class 'panel.theme.materi..., name='Styles', sizing_mode='stretch_width', type=<class 'dict'>)
        [12] ListInput(description='List of stylesheets d..., design=<class 'panel.theme.materi..., name='Stylesheets', sizing_mode='stretch_width', type=<class 'list'>)
        [13] ListInput(description='List of arbitrary t..., design=<class 'panel.theme.materi..., name='Tags', sizing_mode='stretch_width', type=<class 'list'>)
        [14] IntInput(description='The width of the componen..., design=<class 'panel.theme.materi..., name='Width', sizing_mode='stretch_width', start=0)
        [15] Select(description='Describes how the compone..., design=<class 'panel.theme.materi..., name='Width policy', options=OrderedDict([('auto', ...]), sizing_mode='stretch_width', value='auto')
        [16] Select(description='Describes how the compone..., design=<class 'panel.theme.materi..., name='Height policy', options=OrderedDict([('auto', ...]), sizing_mode='stretch_width', value='auto')
        [17] Select(description='How the component should ..., design=<class 'panel.theme.materi..., name='Sizing mode', options=OrderedDict([('fixed', ...]), sizing_mode='stretch_width', value='stretch_width')
        [18] Checkbox(design=<class 'panel.theme.materi..., name='Visible', sizing_mode='stretch_width', value=True)
        [19] Checkbox(design=<class 'panel.theme.materi..., name='Loading', sizing_mode='stretch_width')
        [20] Row(design=<class 'panel.theme.materi..., width=300)
            [0] LiteralInput(description='Defines the l..., design=<class 'panel.theme.materi..., margin=(5, 0, 5, 10), name='Default layout', sizing_mode='stretch_width', value=<class 'panel.layout.base....)
            [1] Toggle(align='end', button_type='primary', design=<class 'panel.theme.materi..., height_policy='fit', margin=(0, 0, 5, 10), max_height=30, max_width=20, name='⋮', sizing_mode='stretch_width')
        [21] LiteralInput(description='The object being wrapped,..., design=<class 'panel.theme.materi..., name='Object', sizing_mode='stretch_width', value='Hello World')
        [22] Checkbox(design=<class 'panel.theme.materi..., name='Enable streaming', sizing_mode='stretch_width')
        [23] Checkbox(design=<class 'panel.theme.materi..., name='Dedent', sizing_mode='stretch_width', value=True)
        [24] Checkbox(design=<class 'panel.theme.materi..., name='Disable math', sizing_mode='stretch_width')
        [25] ListInput(description="Markdown extension t..., design=<class 'panel.theme.materi..., name='Extensions', sizing_mode='stretch_width', type=<class 'list'>, value=['extra', 'smarty', ...])
        [26] Checkbox(design=<class 'panel.theme.materi..., name='Hard line break', sizing_mode='stretch_width')
        [27] ListInput(description='Additional markdown-it-py..., design=<class 'panel.theme.materi..., name='Plugins', sizing_mode='stretch_width', type=<class 'list'>)
        [28] Select(description='Markdown renderer i..., design=<class 'panel.theme.materi..., name='Renderer', options=OrderedDict([('markdown-it...]), sizing_mode='stretch_width', value='markdown-it')
        [29] DictInput(description='Options to pass t..., design=<class 'panel.theme.materi..., name='Renderer options', sizing_mode='stretch_width', type=<class 'dict'>)
    [1] HTML(str, design=<class 'panel.theme.materi..., sizing_mode='stretch_width')

In [22]:
import panel as pn
import numpy as np

from matplotlib.figure import Figure

ACCENT = "goldenrod"
LOGO = "https://assets.holoviz.org/panel/tutorials/matplotlib-logo.png"

pn.extension(sizing_mode="stretch_width")

data = np.random.normal(1, 1, size=100)
fig = Figure(figsize=(8, 4))
ax = fig.subplots()
ax.hist(data, bins=20, color=ACCENT)

component = pn.pane.Matplotlib(fig, format='svg', sizing_mode='scale_both')

pn.template.FastListTemplate(
    title="My App", sidebar=[LOGO], main=[component], accent=ACCENT
).servable()

FastListTemplate
    [js_area] HTML(None, design=<class 'panel.theme.materi..., height=0, margin=0, sizing_mode='fixed', width=0)
    [actions] TemplateActions()
    [browser_info] BrowserInfo(dark_mode=False, device_pixel_ratio=1.5, language='en-US', timezone='Europe/Dublin', timezone_offset=0, webdriver=False, webgl=True)
    [busy_indicator] LoadingSpinner(height=20, width=20)
    [main-132814398186896] Matplotlib(Figure, design=<class 'panel.theme.materi..., format='svg', sizing_mode='scale_both')
    [nav-132814193901008] PNG(str, design=<class 'panel.theme.materi..., sizing_mode='stretch_width')

## Example Dashboard

<style>div.container { width: 100% }</style>
<img style="float:left;  vertical-align:text-bottom;" height="65" width="172" src="https://raw.githubusercontent.com/holoviz/holoviz/master/doc/_static/holoviz-logo-unstacked.svg" />
<div style="float:right; vertical-align:text-bottom;"><h2>Tutorial 4. Making dashboards</h2></div>


This tutorial demonstrates the Easiest Way to Create an Interactive Dashboard in Python from any DataFrame.  If you already know some Pandas, you can almost immediately use `hvPlot` `.interactive` and `Panel` to turn your DataFrame processing pipeline into a dashboard! It just takes a few lines of familiar code to make an interactive dashboard like this:
![Data App](https://github.com/holoviz-community/HoloViz_KDD2022/blob/main/assets/easy-dataframe-dashboards.gif?raw=1)

## Import and configure packages

Please note that in **Colab** you will need to `!pip install panel hvplot`.

In [5]:
def environment():
    try:
        get_ipython()
        print('notebook')
        return str(get_ipython())
    except:
        print('server')
        return 'server'
env = environment()

if env=="server":
   theme="fast"
else:
   theme="simple"

if 'google.colab' in env:
    print('Running on CoLab')
    !pip install panel hvplot
    !pip install bokeh_sampledata

notebook
Running on CoLab
Requirement already satisfied: panel in /usr/local/lib/python3.11/dist-packages (1.6.0)
Requirement already satisfied: hvplot in /usr/local/lib/python3.11/dist-packages (0.11.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from panel) (6.2.0)
Requirement already satisfied: bokeh<3.7.0,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from panel) (3.6.2)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.11/dist-packages (from panel) (2.0.3)
Requirement already satisfied: markdown in /usr/local/lib/python3.11/dist-packages (from panel) (3.7)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.11/dist-packages (from panel) (3.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.11/dist-packages (from panel) (0.4.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from panel) (24.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from panel) (2.2.2)
Requirement already satisfied: param<3.0,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from panel) (2.2.0)
Requirement already satisfied: pyviz-comms>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from panel) (3.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from panel) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from panel) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from panel) (4.12.2)
Requirement already satisfied: colorcet>=2 in /usr/local/lib/python3.11/dist-packages (from hvplot) (3.1.0)
Requirement already satisfied: holoviews>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from hvplot) (1.20.0)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.11/dist-packages (from hvplot) (1.26.4)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from bokeh<3.7.0,>=3.5.0->panel) (3.1.5)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.11/dist-packages (from bokeh<3.7.0,>=3.5.0->panel) (1.3.1)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from bokeh<3.7.0,>=3.5.0->panel) (11.1.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.11/dist-packages (from bokeh<3.7.0,>=3.5.0->panel) (6.0.2)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.11/dist-packages (from bokeh<3.7.0,>=3.5.0->panel) (6.4.2)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.11/dist-packages (from bokeh<3.7.0,>=3.5.0->panel) (2025.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->panel) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->panel) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->panel) (2025.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach->panel) (0.5.1)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.11/dist-packages (from linkify-it-py->panel) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py->panel) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->panel) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->panel) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->panel) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->panel) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2>=2.9->bokeh<3.7.0,>=3.5.0->panel) (3.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2->panel) (1.17.0)
Collecting bokeh_sampledata
  Downloading bokeh_sampledata-2024.2-py3-none-any.whl.metadata (2.6 kB)
Collecting icalendar (from bokeh_sampledata)
  Downloading icalendar-6.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from bokeh_sampledata) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->bokeh_sampledata) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->bokeh_sampledata) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->bokeh_sampledata) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->bokeh_sampledata) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh_sampledata) (1.17.0)
Downloading bokeh_sampledata-2024.2-py3-none-any.whl (17.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 46.9 MB/s eta 0:00:00
Downloading icalendar-6.1.1-py3-none-any.whl (200 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.6/200.6 kB 15.6 MB/s eta 0:00:00
Installing collected packages: icalendar, bokeh_sampledata
Successfully installed bokeh_sampledata-2024.2 icalendar-6.1.1

In [6]:
import panel as pn

pn.extension('tabulator', sizing_mode="stretch_width")

<ipython-input-6-cd6ed36f5344>:3: UserWarning: Using Panel interactively in Colab notebooks requires the jupyter_bokeh package to be installed. Install it with:

    !pip install jupyter_bokeh

and try again.
  pn.extension('tabulator', sizing_mode="stretch_width")

In [7]:
import hvplot.pandas
import holoviews as hv

hv.extension('bokeh')

## Load Data

In [8]:
from bokeh.sampledata.autompg import autompg_clean as df
df.head()

,mpg,cyl,displ,hp,weight,accel,yr,origin,name,mfr
0,18.0,8,307.0,130,3504,12.0,70,North America,chevrolet chevelle malibu,chevrolet
1,15.0,8,350.0,165,3693,11.5,70,North America,buick skylark 320,buick
2,18.0,8,318.0,150,3436,11.0,70,North America,plymouth satellite,plymouth
3,16.0,8,304.0,150,3433,12.0,70,North America,amc rebel sst,amc
4,17.0,8,302.0,140,3449,10.5,70,North America,ford torino,ford

## Define DataFrame Pipeline

In [9]:
(
    df[
        (df.cyl == 4) &
        (df.mfr.isin(['ford','chevrolet']))
    ]
    .groupby(['origin', 'cyl', 'mfr', 'yr'])['hp'].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='yr')
).head(1)

          origin  cyl        mfr  yr    hp
0  North America    4  chevrolet  71  81.0

## Make DataFrame Pipeline Interactive

What if we would like to turn the values of cyl, the values of mfr, and the variable hp into interactive widgets that we can change and control? Is it possible? Yes, it is, and with hvPlot it’s not even difficult. Here are the steps:

- First, we need to wrap our dataframe with `.interactive()`: `idf = df.interactive()`, so that this dataframe becomes interactive and we can use Panel widgets on this dataframe.

“.interactive stores a copy of your pipeline (series of method calls or other expressions on your data) and dynamically replays the pipeline whenever that widget changes.”

In [10]:
idf = df.interactive()

Define [Panel widgets](https://panel.holoviz.org/reference/index.html#widgets)

- Second, we can define the panel widgets we would like to use. Here I defined a panel widget for cylinders, a widget for the manufacturer, and a widget to select the y axis.

In [11]:
cylinders = pn.widgets.IntSlider(name='Cylinders', start=4, end=8, step=2)
cylinders

IntSlider(end=8, name='Cylinders', sizing_mode='stretch_width', start=4, step=2, value=4)

In [12]:
mfr = pn.widgets.ToggleGroup(
    name='MFR',
    options=['ford', 'chevrolet', 'honda', 'toyota', 'audi'],
    value=['ford', 'chevrolet', 'honda', 'toyota', 'audi'],
    button_type='success')
mfr

CheckButtonGroup(button_type='success', name='MFR', options=['ford', 'chevrolet', ...], sizing_mode='stretch_width', value=['ford', 'chevrolet', ...])

In [13]:
yaxis = pn.widgets.RadioButtonGroup(
    name='Y axis',
    options=['hp', 'weight'],
    button_type='success'
)
yaxis

RadioButtonGroup(button_type='success', name='Y axis', options=['hp', 'weight'], sizing_mode='stretch_width', value='hp')

- Finally, we can replace the values or variables from the original Pandas pipeline to these widgets we just defined. We define the output of the pipeline as ipipeline:

In [14]:
ipipeline = (
    idf[
        (idf.cyl == cylinders) &
        (idf.mfr.isin(mfr))
    ]
    .groupby(['origin', 'mpg'])[yaxis].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='mpg')
    .reset_index(drop=True)
)
ipipeline.head()

## Pipe to Table

In [15]:
itable = ipipeline.pipe(pn.widgets.Tabulator, pagination='remote', page_size=10, theme=theme)
itable

Check out the [Tabulator Reference Guide](https://panel.holoviz.org/reference/widgets/Tabulator.html) for more inspiration.

## Pipe to hvplot

In [17]:
PALETTE = ["#ff6f69", "#ffcc5c", "#88d8b0", ]
# pn.Row(
#     pn.layout.HSpacer(height=50, background=PALETTE[0]),
#     pn.layout.HSpacer(height=50, background=PALETTE[1]),
#     pn.layout.HSpacer(height=50, background=PALETTE[2]),
# )
pn.Row(
    pn.pane.HTML(f'<div style="background-color:{PALETTE[0]}; width:100px; height:50px;"></div>'),
    pn.pane.HTML(f'<div style="background-color:{PALETTE[1]}; width:100px; height:50px;"></div>'),
    pn.pane.HTML(f'<div style="background-color:{PALETTE[2]}; width:100px; height:50px;"></div>'),
)

Row(sizing_mode='stretch_width')
    [0] HTML(str, sizing_mode='stretch_width')
    [1] HTML(str, sizing_mode='stretch_width')
    [2] HTML(str, sizing_mode='stretch_width')

In [18]:
ihvplot = ipipeline.hvplot(x='mpg', y=yaxis, by='origin', color=PALETTE, line_width=6, height=400)
ihvplot

WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.
WARNING:param.Row01085: Comm received message that could not be deserialized.
WARNING:param.Row01085:Comm received message that could not be deserialized.

## Layout using Panel

In [19]:
pn.Column(
    pn.Row(
        cylinders, mfr, yaxis
    ),
    ihvplot.panel(),
    itable.panel()
)

Column(sizing_mode='stretch_width')
    [0] Row(sizing_mode='stretch_width')
        [0] IntSlider(end=8, name='Cylinders', sizing_mode='stretch_width', start=4, step=2, value=4)
        [1] CheckButtonGroup(button_type='success', name='MFR', options=['ford', 'chevrolet', ...], sizing_mode='stretch_width', value=['ford', 'chevrolet', ...])
        [2] RadioButtonGroup(button_type='success', name='Y axis', options=['hp', 'weight'], sizing_mode='stretch_width', value='hp')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False, sizing_mode='stretch_width')
    [2] ParamFunction(function, _pane=Tabulator, defer_load=False, sizing_mode='stretch_width')

## Layout using Template

Here we use the [FastListTemplate](https://panel.holoviz.org/reference/templates/FastListTemplate.html#templates-gallery-fastlisttemplate).

In [20]:
template = pn.template.FastListTemplate(
    title='Interactive DataFrame Dashboards with hvplot .interactive',
    sidebar=[cylinders, 'Manufacturers', mfr, 'Y axis' , yaxis],
    main=[ihvplot.panel(), itable.panel()],
    accent_base_color="#88d8b0",
    header_background="#88d8b0",
)
# template.show()
template.servable();

Please note that to get the Tabulator table styled nicely for dark mode you can set `theme='fast'` when you define the `itable`. It won't work in the notebook though.

To *serve the notebook* run `panel serve 04_Dashboard.ipynb`.

<div class="alert alert-info">
<h4>Exercise</h4>
    
Take a look at the [Panel widget docs](https://panel.holoviz.org/reference/index.html#widgets). And change the three widgets above to different types of widgets of your choice.  
        
<details><summary><i><u>(Solution)</u><i></summary><br>
    
```python

cylinders = pn.widgets.IntInput(name='Cylinders', value=4, step=2, start=4, end=8)
mfr = pn.widgets.CheckBoxGroup(
    name='MFR',
    options=['ford', 'chevrolet', 'honda', 'toyota', 'audi'],
    value=['ford', 'chevrolet', 'honda', 'toyota', 'audi']
)
yaxis = pn.widgets.RadioBoxGroup(
    name='Y axis',
    options=['hp', 'weight'],
)
    
    
```

</details>
</div>

<div class="alert alert-info">
<h4>Exercise</h4>
    
Add a widget to select origin in the example above.

<details><summary><i><u>(Solution)</u><i></summary><br>
    
```python

origin = pn.widgets.ToggleGroup(
    name='Origin',
    options=['North America', 'Asia', 'Europe'],
    value=['North America', 'Asia', 'Europe'],
    button_type='success')
origin
    
ipipeline = (
    idf[
        (idf.cyl == cylinders) &
        (idf.mfr.isin(mfr)) &
        (idf.origin.isin(origin))
    ]
    .groupby(['origin', 'mpg'])[yaxis].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='mpg')  
    .reset_index(drop=True)
)
ipipeline.head()
    
```

</details>
</div>

<div class="alert alert-info">
<h4>Exercise</h4>
    
Try save this notebook to a Python file, or copy and paste the relevant code to a Python file.
    
Then serve the dashboard from the Python file: `panel serve 04_Dashboard.py`.

</details>
</div>

<div class="alert alert-info">
<h4>Reading time </h4>
    
Read the [Panel documentation](https://panel.holoviz.org/) and let us know if you have any questions.
</div>