<a href="https://colab.research.google.com/github/venkataratnamb20/quicksilicon/blob/notebooks/notebooks/vlsi/pyadc/pyadc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ADC

In [1]:
from dataclasses import dataclass

@dataclass
class Adc:
    nbit: int = 10
    vrefp: float = 1.0
    vrefm: float = 0.0
    fs: float = 10e3
    # def __post_init__(self, nbit: int = 10, vrefp: float = 1.0, vrefm: float = 0.0, fs: float = 1e3):
    #     self.nbit = nbit
    #     self.vrefp = vrefp
    #     self.vrefm = vrefm
    #     self.fs = fs

    @property
    def vref(self):
        return self.vrefp - self.vrefm

    @property
    def qlevels(self):
        return 2**self.nbit

    @property
    def lsb(self):
        return self.vref / (self.qlevels - 1)

    @property
    def sqnref(self):
        return 6.02 * self.nbit + 1.76

    @property
    def fclk(self):
        return self.fs * (self.nbit + 2)

    @property
    def tsample(self):
        return 1 / self.fs

    def convert(self, vin: float = 0.0):
        if vin > self.vrefp:
            vin = self.vref
        elif vin < self.vrefm:
            vin = self.vrefm
        return round(vin / self.lsb)

    def sar(self, vin: float = 0.0):
        raise NotImplementedError("Wait for the best tohappen!!!")

    def __str__(self):
        return f"""
        ADC(nbit = {self.nbit}, vrefp = {self.vrefp}, vrefm = {self.vrefm}, fs = {self.fs})"""

    def __repr__(self):
        return self.__str__()

    def __call__(self, vin: float = 0.0):
        return self.convert(vin)


adc = Adc(nbit = 10, vrefp = 1.0, vrefm = 0.0, fs = 10e3)
print(adc)

        ADC(nbit = 10, vrefp = 1.0, vrefm = 0.0, fs = 10000.0)

In [2]:
nbit = 10

for i in range(nbit + 2):
    vin = (2**i) * adc.lsb
    print(f"{vin} -> {adc(vin)}")

0.0009775171065493646 -> 1
0.0019550342130987292 -> 2
0.0039100684261974585 -> 4
0.007820136852394917 -> 8
0.015640273704789834 -> 16
0.03128054740957967 -> 32
0.06256109481915934 -> 64
0.12512218963831867 -> 128
0.25024437927663734 -> 256
0.5004887585532747 -> 512
1.0009775171065494 -> 1023
2.0019550342130987 -> 1023

In [3]:
class SarAdc(Adc):
    def __init__(self, nbit: int = 10, vrefp: float = 0.0, vrefm: float = 0.0, fs: float = 10e3, *args, **kwargs):
        super().__init__(nbit, vrefp, vrefm, fs, *args, **kwargs)
        self.nbit = nbit
        self.vrefp = vrefp
        self.vrefm = vrefm
        self.fs = fs
        self. low_level = self.vrefm
        self.high_level = self.vrefp
        self.code = []

    def comparator(self, vin: float = 0.0, vthresh: float = 0.0):
        return vin > vthresh

    def sar(self, vin: float = 0, *args, **kwargs):
        """Successive Approximation algorithm

        Args:
            vin (float, optional): input voltage. Defaults to 0.
            lower_level (float): lower level voltage. Defaults to 0.
            upper_level (float): upper level voltage. Defaults to 0.

        Returns:
            int: output voltage.
        """
        # nbit = kwargs.get("nbit", 10)
        # vrefm, vrefp = kwargs.get("vrefm", self.vrefm), kwargs.get("vrefp", self.vrefp)
        low_level, high_level = self.vrefm, self.vrefp
        code = []
        def algorithm(low_level: float = self.vrefm, high_level: float  =self.vrefp):
            # vthresh = low_level + (high_level - low_level) / 2
            vthresh = (high_level - low_level) / 2
            # print(f"levels:: low: {low_level} high: {high_level}")
            # print(f"vthresh: {vthresh}")
            decision = int(vin > low_level + vthresh)
            # decision = vin >= vthresh
            code.append(decision)
            if not decision:
                high_level = high_level - vthresh
            else:
                low_level = low_level + vthresh
            if len(code) == self.nbit:
                return code
            else:
                return algorithm(low_level, high_level)
        return algorithm(low_level, high_level)

    def __call__(self, vin: float = 0.0):
        self.code = []
        return self.sar(vin, self.vrefm, self.vrefp)


if __name__ == "__main__":
    saradc = SarAdc()
    print(f"nbit: {saradc.nbit}:: lsb: {saradc.lsb}")
    print(saradc(16 * adc.lsb))
    nbit = 10
    get_analog_from_bits_array = lambda code_list: int(''.join([str(bit) for bit in code_list]), 2)

    for i in range(nbit + 2):
        vin = (2**i) * adc.lsb
        print(f"{2**i}: {vin} \t->\t {saradc(vin)}::{get_analog_from_bits_array(saradc(vin))}")

nbit: 10:: lsb: 0.0
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
1: 0.0009775171065493646 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
2: 0.0019550342130987292 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
4: 0.0039100684261974585 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
8: 0.007820136852394917 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
16: 0.015640273704789834 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
32: 0.03128054740957967 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
64: 0.06256109481915934 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
128: 0.12512218963831867 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
256: 0.25024437927663734 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
512: 0.5004887585532747 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
1024: 1.0009775171065494 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
2048: 2.0019550342130987 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023

## SAR

### SAR: Logic

In [4]:
def sar(vin, *args, **kwargs):
    """Successive Approximation algorithm

    """
    nbit = kwargs.get("nbit", 10)
    vrefm, vrefp = kwargs.get("vrefm", 0), kwargs.get("vrefp", 1.0)
    low_level, high_level = vrefm, vrefp
    lsb = (vrefp - vrefm) / (2**nbit - 1)
    code = []
    def algorithm(vin, low_level, high_level):
        # vthresh = low_level + (high_level - low_level) / 2
        vthresh = (high_level - low_level) / 2
        # print(f"levels:: low: {low_level} high: {high_level}")
        # print(f"vthresh: {vthresh}")
        decision = int(vin > low_level + vthresh)
        # decision = vin >= vthresh
        code.append(decision)
        if not decision:
            high_level = high_level - vthresh
        else:
            low_level = low_level + vthresh
        if len(code) == nbit:
            return "".join(str(bit) for bit in code)
        else:
            return algorithm(vin, low_level, high_level)
    return algorithm(vin, low_level, high_level)

sar(0.75)

'1011111111'

In [5]:
nbit = 12
vrefp = 1.5

adc = Adc(nbit = nbit, vrefp = vrefp)
print(adc)

get_analog_from_bits_array = lambda code_list: int(''.join([str(bit) for bit in code_list]), 2)

for i in range(nbit + 2):
    vin = (2**i) * adc.lsb
    # print(f"{vin} -> {sar(vin)}::{int(''.join([str(bit) for bit in sar(vin)]), 2)}")
    print(f"{2**i}: {vin} -> {sar(vin, nbit= nbit, vrefp = vrefp)}::{get_analog_from_bits_array(sar(vin, nbit= nbit, vrefp = vrefp))}")

        ADC(nbit = 12, vrefp = 1.5, vrefm = 0.0, fs = 10000.0)
1: 0.0003663003663003663 -> 000000000001::1
2: 0.0007326007326007326 -> 000000000010::2
4: 0.0014652014652014652 -> 000000000100::4
8: 0.0029304029304029304 -> 000000001000::8
16: 0.005860805860805861 -> 000000010000::16
32: 0.011721611721611722 -> 000000100000::32
64: 0.023443223443223443 -> 000001000000::64
128: 0.046886446886446886 -> 000010000000::128
256: 0.09377289377289377 -> 000100000000::256
512: 0.18754578754578755 -> 001000000000::512
1024: 0.3750915750915751 -> 010000000000::1024
2048: 0.7501831501831502 -> 100000000000::2048
4096: 1.5003663003663004 -> 111111111111::4095
8192: 3.0007326007326007 -> 111111111111::4095

In [6]:
# int("110", 2)
# int(''.join(sar(0)), 2)
# ''.join([1, 1, 0])

### SAR: test

In [7]:
import unittest

class TestSar(unittest.TestCase):
    def setUp(self):
        self.nbit = 10
        self.vrefp = 1.0
        self.vrefm = 0.0
        self.vref = self.vrefp - self.vrefm
        self.qlevels = 2**self.nbit
        self.lsb = self.vref / (self.qlevels - 1)


        self.get_analog_from_bits_array = lambda code_list: int(''.join([str(bit) for bit in code_list]), 2)

    def test_fullscale_code(self):
        self.assertAlmostEqual(self.get_analog_from_bits_array(sar(self.vrefp)), self.qlevels - 1)

    def test_higher_than_fullscale_code(self):
        self.assertAlmostEqual(self.get_analog_from_bits_array(sar(2 * self.vrefp)), self.qlevels - 1)

    def test_negative_vin(self):
        self.assertAlmostEqual(self.get_analog_from_bits_array(sar(-10 * self.lsb)), 0)

    def test_bit_levels(self):
        for i in range(self.nbit):
            vin = (2**i) * self.lsb
            _ideal_code = self.get_analog_from_bits_array(sar(vin, nbit = self.nbit))
            self.assertAlmostEqual(_ideal_code, 2**i)

    def test_all_levels(self):
        for i in range(2**self.nbit):
            vin = i * self.lsb
            # print(f"{vin} -> {sar(vin)}")
            _ideal_code = self.get_analog_from_bits_array(sar(vin, nbit = self.nbit))
            self.assertAlmostEqual(_ideal_code, i)



if __name__ == "__main__":
    unittest.main(argv=[''], exit=False, verbosity=2)

test_all_levels (__main__.TestSar.test_all_levels) ... ok
test_bit_levels (__main__.TestSar.test_bit_levels) ... ok
test_fullscale_code (__main__.TestSar.test_fullscale_code) ... ok
test_higher_than_fullscale_code (__main__.TestSar.test_higher_than_fullscale_code) ... ok
test_negative_vin (__main__.TestSar.test_negative_vin) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.029s

OK

In [8]:
print(get_analog_from_bits_array(sar(2**0 * adc.lsb, nbit = adc.nbit)))
assert get_analog_from_bits_array(sar(2**0 * adc.lsb, nbit = adc.nbit)) == 2**0
range(2**nbit)[-1]

1

4095

In [9]:
code = "".join([str(bit) for bit in sar(2**0 * adc.lsb, nbit = adc.nbit)])
assert int(code, 2) == 2**0

In [10]:
import ipywidgets as ipw

vrefp_max = 2.5
@ipw.interact(vin = (0, vrefp_max, 0.1), nbit = (1, 15, 1), vrefp = (0.0, vrefp_max, 0.5), vrefm = (0.0, vrefp_max, 0.5))
def get_sar(vin, nbit, vrefp, vrefm):
    return sar(vin, nbit=nbit, vrefp=vrefp, vrefm=vrefm)

interactive(children=(FloatSlider(value=1.2000000000000002, description='vin', max=2.5), IntSlider(value=8, de…

## SAR: Calculations

### Setup

In [11]:
import os

from pathlib import Path

# data_path = Path(os.getcwd()).parent / "data"
data_path = Path(os.getcwd()) / "data"

# create data_path if does nto exit
data_path.mkdir(parents=True, exist_ok=True)

In [12]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(context="notebook", style="darkgrid", palette="pastel")

### DACOUT

In [13]:
nbit = 12
vrefp = 1.5

lsb = 2 * vrefp / (2**nbit - 1)
print(f"lsb: {lsb}")

vcm = 0.5 * vrefp
vin = 0.75
vinp = vcm + 0.5 * vin
vinm = vcm - 0.5 * vin

vthreshp = vrefp / 2
vthreshm = vrefp / 2

dacoutp = vcm + vthreshp - vinp
dacoutm = vcm + vthreshm - vinm

dacoutp, dacoutm

lsb: 0.0007326007326007326

(0.375, 1.125)

In [14]:
vfs = 1.49708

err = vrefp - vfs

err, err / lsb

(0.0029200000000000337, 3.985800000000046)

In [15]:
ideal_fs = 2**nbit - 1
adcout_fsm, adcout_fsp = 4095, 4076

errp, errm = ideal_fs - adcout_fsm, ideal_fs - adcout_fsp

errp, errm

(0, 19)

In [16]:
vrefp = 1.5
adc_diff = Adc(
    nbit = 12,
    vrefp = 2*vrefp,
    vrefm = 0.0,
    fs = 10e3
)
adc_diff_convert = lambda vin, vrefp=1.0: adc_diff.convert(vrefp + vin)
for i in range(nbit):
    _vin = 2**i * adc_diff.lsb
    code = adc_diff_convert(_vin, vrefp)
    print(f"i: {i}\t::\tvin:{_vin}::code: {code}")

i: 0	::	vin:0.0007326007326007326::code: 2048
i: 1	::	vin:0.0014652014652014652::code: 2050
i: 2	::	vin:0.0029304029304029304::code: 2052
i: 3	::	vin:0.005860805860805861::code: 2056
i: 4	::	vin:0.011721611721611722::code: 2064
i: 5	::	vin:0.023443223443223443::code: 2080
i: 6	::	vin:0.046886446886446886::code: 2112
i: 7	::	vin:0.09377289377289377::code: 2176
i: 8	::	vin:0.18754578754578755::code: 2304
i: 9	::	vin:0.3750915750915751::code: 2560
i: 10	::	vin:0.7501831501831502::code: 3072
i: 11	::	vin:1.5003663003663004::code: 4095

In [69]:
from pathlib import Path

# data_path = Path(os.getcwd()).parent / "data"
data_path = Path(os.getcwd()) / "data"
def process_adc_sim_data(filename: os.PathLike, **kwargs):
    vin_key = kwargs.get("vin_key", "adcoutp_at_eoc_x")
    vrefp = kwargs.get("vrefp", 1.5)
    try:
        # /content/data/saradc_out_linearity_bitshift250128.csv
        adcout_sim = pd.read_csv(filename)
        adcout_sim.columns = adcout_sim.columns.str.strip().str.lower().str.replace(" ", "_")
        adcout_sim["ideal_outp"] = adcout_sim[vin_key].apply(lambda x: adc_diff_convert(x, vrefp))
        adcout_sim["errorp"] = adcout_sim["adcoutp_at_eoc_y"] - adcout_sim["ideal_outp"]
        return adcout_sim
    except FileNotFoundError:
        print(f"File not found: {filename}")
        return

adcout_sim = process_adc_sim_data(data_path / "saradc_out_linearity_bitshift250128.csv")

adcout_sim

,adcoutm_at_eoc_x,adcoutm_at_eoc_y,adcoutp_at_eoc_x,adcoutp_at_eoc_y,ideal_outp,errorp
0,-1.500000,4095,-1.500000,0,0,0
1,-0.750000,3072,-0.750000,1023,1024,-1
2,-0.375000,2559,-0.375000,1536,1536,0
3,-0.187500,2303,-0.187500,1792,1792,0
4,-0.093750,2175,-0.093750,1920,1920,0
5,-0.046875,2111,-0.046875,1984,1984,0
6,-0.023438,2080,-0.023438,2015,2016,-1
7,-0.011719,2065,-0.011719,2030,2032,-2
8,-0.005859,2056,-0.005859,2039,2040,-1
9,-0.002930,2052,-0.002930,2043,2044,-1
10,-0.001465,2051,-0.001465,2044,2046,-2
11,-0.000732,2049,-0.000732,2046,2047,-1
12,-0.000366,2049,-0.000366,2046,2047,-1
13,0.000000,2048,0.000000,2047,2048,-1
14,0.000366,2048,0.000366,2047,2048,-1
15,0.000732,2048,0.000732,2047,2048,-1
16,0.001465,2048,0.001465,2047,2049,-2
17,0.002930,2048,0.002930,2047,2051,-4
18,0.005859,2048,0.005859,2047,2055,-8
19,0.011719,2048,0.011719,2047,2063,-16
20,0.023438,2048,0.023438,2047,2079,-32
21,0.046875,1984,0.046875,2111,2111,0
22,0.093750,1919,0.093750,2176,2175,1
23,0.187500,1792,0.187500,2303,2303,0
24,0.375000,1535,0.375000,2560,2559,1
25,0.750000,1027,0.750000,3068,3071,-3
26,1.500000,19,1.500000,4076,4095,-19

In [71]:
process_adc_sim_data("/content/data/saradc_out_linearity_bitshift250131_allSch_nodacBuff.csv")

,adcoutm_at_eoc_x,adcoutm_at_eoc_y,adcoutp_at_eoc_x,adcoutp_at_eoc_y,ideal_outp,errorp
0,-1.500000,4095,-1.500000,0,0,0
1,-0.750000,3075,-0.750000,1020,1024,-4
2,-0.375000,2559,-0.375000,1536,1536,0
3,-0.187500,2301,-0.187500,1794,1792,2
4,-0.093750,2167,-0.093750,1928,1920,8
5,-0.046875,2101,-0.046875,1994,1984,10
6,-0.023438,2074,-0.023438,2021,2016,5
7,-0.011719,2057,-0.011719,2038,2032,6
8,-0.005859,2051,-0.005859,2044,2040,4
9,-0.002930,2048,-0.002930,2047,2044,3
10,-0.001465,2048,-0.001465,2047,2046,1
11,-0.000732,2048,-0.000732,2047,2047,0
12,-0.000366,2048,-0.000366,2047,2047,0
13,0.000000,2048,0.000000,2047,2048,-1
14,0.000366,2048,0.000366,2047,2048,-1
15,0.000732,2047,0.000732,2048,2048,0
16,0.001465,2047,0.001465,2048,2049,-1
17,0.002930,2047,0.002930,2048,2051,-3
18,0.005859,2047,0.005859,2048,2055,-7
19,0.011719,2038,0.011719,2057,2063,-6
20,0.023438,2024,0.023438,2071,2079,-8
21,0.046875,1996,0.046875,2099,2111,-12
22,0.093750,1929,0.093750,2166,2175,-9
23,0.187500,1795,0.187500,2300,2303,-3
24,0.375000,1535,0.375000,2560,2559,1
25,0.750000,1023,0.750000,3072,3071,1
26,1.500000,7,1.500000,4088,4095,-7

In [21]:
process_adc_sim_data("/content/data/saradc_out_linearity_bitshift250211_allSch.csv")

,adcoutm_at_eoc_x,adcoutm_at_eoc_y,adcoutp_at_eoc_x,adcoutp_at_eoc_y,ideal_outp,errorp
0,-1.500000,4095,-1.500000,0,0,0
1,-0.750000,3072,-0.750000,1023,1024,-1
2,-0.375000,2559,-0.375000,1536,1536,0
3,-0.187500,2300,-0.187500,1795,1792,3
4,-0.093750,2167,-0.093750,1928,1920,8
5,-0.046875,2104,-0.046875,1991,1984,7
6,-0.023438,2072,-0.023438,2023,2016,7
7,-0.011719,2056,-0.011719,2039,2032,7
8,-0.005859,2049,-0.005859,2046,2040,6
9,-0.002930,2048,-0.002930,2047,2044,3
10,-0.001465,2048,-0.001465,2047,2046,1
11,-0.000732,2048,-0.000732,2047,2047,0
12,-0.000366,2048,-0.000366,2047,2047,0
13,0.000000,2048,0.000000,2047,2048,-1
14,0.000366,2047,0.000366,2048,2048,0
15,0.000732,2047,0.000732,2048,2048,0
16,0.001465,2047,0.001465,2048,2049,-1
17,0.002930,2047,0.002930,2048,2051,-3
18,0.005859,2047,0.005859,2048,2055,-7
19,0.011719,2038,0.011719,2057,2063,-6
20,0.023438,2022,0.023438,2073,2079,-6
21,0.046875,1999,0.046875,2096,2111,-15
22,0.093750,1927,0.093750,2168,2175,-7
23,0.187500,1798,0.187500,2297,2303,-6
24,0.375000,1536,0.375000,2559,2559,0
25,0.750000,1023,0.750000,3072,3071,1
26,1.500000,1,1.500000,4094,4095,-1

In [24]:
adc12 = Adc(nbit = 12, vrefp=3, vrefm = 0)
adc12.qlevels - 1920

2176

In [28]:
# 3 / adc12.qlevels * 1920
vrefp = 1.5
vin = -vrefp / 16
print(f"vin: {vin}")
adc12.convert(vrefp + vin)

vin: -0.09375

1920

In [30]:
_code = sar(vin, nbit = 12, vrefp = vrefp, vrefm = -vrefp)
int(_code, 2)

1919

In [68]:
'0' * adc12.nbit

# convert decimal to 12bit binary
get_binary = lambda x, nbit = 10: bin(x)[2:].zfill(nbit)
_codes_dict = {2**i: get_binary(2**i, nbit=nbit) for i in range(nbit)}
for i in range(nbit):
    _code = get_binary(2**i, nbit=12)
    # _codes.append(_code)
    print(f"{2**i}:\t{_code}")

1:	000000000001
2:	000000000010
4:	000000000100
8:	000000001000
16:	000000010000
32:	000000100000
64:	000001000000
128:	000010000000
256:	000100000000
512:	001000000000
1024:	010000000000
2048:	100000000000

In [47]:
for ql, code in _codes_dict.items():
    _vanalog = ql * adc12.lsb - vrefp
    print(f"{ql}:\t {code}::\t{_vanalog}")

1:	 000000000001::	-1.4992673992673993
2:	 000000000010::	-1.4985347985347985
4:	 000000000100::	-1.497069597069597
8:	 000000001000::	-1.4941391941391942
16:	 000000010000::	-1.4882783882783883
32:	 000000100000::	-1.4765567765567766
64:	 000001000000::	-1.453113553113553
128:	 000010000000::	-1.4062271062271061
256:	 000100000000::	-1.3124542124542125
512:	 001000000000::	-1.124908424908425
1024:	 010000000000::	-0.7498168498168498
2048:	 100000000000::	0.000366300366300365

In [72]:
vrefp = 1.5

adcout_df = process_adc_sim_data("/content/data/saradc_out_linearity_bitshift250211_allSch_v2.csv")

if adcout_df is None:
    print("File not found")
    exit()

adcout_df['vin'] = adcout_df['adcoutp_at_eoc_x'] - vrefp


adc_diff_convert_lamd = np.vectorize(adc_diff_convert)
adcout_df['ideal_outm'] = adc_diff_convert_lamd(adcout_df['vin'], vrefp)
adcout_df['errorm'] = adcout_df['adcoutm_at_eoc_y'] - adcout_df['ideal_outm']
adcout_df[[col for col in adcout_df.columns if 'm' in col]]

    adcoutm_at_eoc_x  adcoutm_at_eoc_y  ideal_outm  errorm
0           0.000732                 1           1       0
1           0.001465                 3           2       1
2           0.002930                 3           4      -1
3           0.005859                 3           8      -5
4           0.011719                15          16      -1
5           0.023438                33          32       1
6           0.046875                63          64      -1
7           0.093750               124         128      -4
8           0.187500               255         256      -1
9           0.375000               511         512      -1
10          0.750000              1023        1024      -1
11          1.500000              2048        2048       0
12          3.000000              4095        4095       0

In [63]:
vrefp = 1.5

adcout_df = process_adc_sim_data("/content/data/saradc_out_linearity_bitshift250211_allSch_v2_outp.csv")
adcout_df

,adcoutm_at_eoc_x,adcoutm_at_eoc_y,adcoutp_at_eoc_x,adcoutp_at_eoc_y,ideal_outp,errorp
0,-1.499268,4095,-1.499268,0,1,-1
1,-1.498535,4095,-1.498535,0,2,-2
2,-1.497070,4095,-1.497070,0,4,-4
3,-1.494141,4095,-1.494141,0,8,-8
4,-1.488281,4089,-1.488281,6,16,-10
5,-1.476562,4071,-1.476562,24,32,-8
6,-1.453125,4032,-1.453125,63,64,-1
7,-1.406250,3972,-1.406250,123,128,-5
8,-1.312500,3840,-1.312500,255,256,-1
9,-1.125000,3584,-1.125000,511,512,-1
10,-0.750000,3072,-0.750000,1023,1024,-1
11,0.000000,2048,0.000000,2047,2048,-1
12,1.500000,1,1.500000,4094,4095,-1

In [41]:
adc12.qlevels

4096

In [18]:
23e-3 / adc_diff.lsb

31.395

In [19]:
(1 * 2**nbit * 20 / 3600) / 24

0.9481481481481482

## DAC

<figure align='center'>

<img src="https://raw.githubusercontent.com/venkataratnamb20/quicksilicon/814a50d602afe777f77213add3ba7da58b9a7f67/notebooks/vlsi/pyadc/dac_digital_representation_table.png" width="500" height="400" />
</figure>

In [20]:
def dac(dig_code):
    return int(dig_code, 2)

# _ideal_code = get_analog_from_bits_array(sar(vin, nbit = 10))

# dac(_ideal_code)
_code = sar(0.5, nbit = 10)
_code, dac(_code)

('0111111111', 511)